# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ce7667e41295bf3828fbbca86f7dee2f82786043ed58cdb66b8107a52f1b32d7819fcd8b7f30d397a8fc9edd9dff79e1bd7b70a880852a0e478e9f19b62615

test:
  secret_key_base: 8839400c44f24fe306d0641ea35d3689890d38dafb1b94b497c8dd90239e292ce697574ded3616a1a3fa338798484a118af8c7353feae28a5e36dda9888739d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
